#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-javax-servlet
Version  : 2.3
Release  : 1
URL      : https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.3/servlet-api-2.3.jar
Source0  : https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.3/servlet-api-2.3.jar
Source1  : https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.3/servlet-api-2.3.pom
Source2  : https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar
Source3  : https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : ISC
Requires: mvn-javax-servlet-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-javax-servlet package.
Group: Data

%description data
data components for the mvn-javax-servlet package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/servlet/servlet-api/2.3
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/javax/servlet/servlet-api/2.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/servlet/servlet-api/2.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/javax/servlet/servlet-api/2.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/servlet/servlet-api/2.5
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/javax/servlet/servlet-api/2.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/servlet/servlet-api/2.5
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/javax/servlet/servlet-api/2.5


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/javax/servlet/servlet-api/2.3/servlet-api-2.3.jar
/usr/share/java/.m2/repository/javax/servlet/servlet-api/2.3/servlet-api-2.3.pom
/usr/share/java/.m2/repository/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar
/usr/share/java/.m2/repository/javax/servlet/servlet-api/2.5/servlet-api-2.5.pom
